import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const START_MARKER = "<!--MRP-META-PROMPT-->";
const END_MARKER = "<!--/MRP-META-PROMPT-->";

/**
 * Known project-level agent config files to scan for.
 * Paths are relative to project root.
 */
export const AGENT_CONFIG_FILES = ["AGENTS.md", "CLAUDE.md"];

export const MRP_META_PROMPT = `${START_MARKER}
## MRP (Model Routine Protocol)

This project uses MRP to manage repeatable agent routines. Before writing a script from scratch, check \`mrp list\` for existing routines.

**When to use MRP:**
- You're about to run a build, test, lint, or deploy step -> check \`mrp list\` first
- You've run the same command 2+ times this session -> create a routine with \`mrp create\`
- A routine failed -> review the output, then judge with \`mrp judge\`
- You need to modify a routine's script -> edit the file directly, then \`mrp edit <id> --commit\`

**Quick reference:**
\`\`\`
mrp list                        - see available routines
mrp run <id>                    - execute a routine
mrp judge <id> "<run_id>" --status success|failure|partial --reason "..."
mrp show <id>                   - view details and run history
mrp create --name <n> --goal "<g>" --non-goals "<ng>" --success-criteria "<id:text>"
mrp --help                      - all commands
\`\`\`
<!-- Generated by MRP CLI. Do not edit this section - it will be overwritten by mrp update. -->
${END_MARKER}`;

/**
 * Inject or replace the MRP meta-prompt section in file content.
 * - If markers exist: replace content between them (inclusive)
 * - If no markers: append to end of content
 * Returns the updated content string.
 */
export function injectMetaPrompt(existingContent: string): string {
  const startIdx = existingContent.indexOf(START_MARKER);
  const endIdx = existingContent.indexOf(END_MARKER);

  if (startIdx !== -1 && endIdx !== -1 && endIdx >= startIdx) {
    const before = existingContent.slice(0, startIdx);
    const after = existingContent.slice(endIdx + END_MARKER.length);
    return before + MRP_META_PROMPT + after;
  }

  const separator =
    existingContent.length > 0 && !existingContent.endsWith("\n\n")
      ? existingContent.endsWith("\n")
        ? "\n"
        : "\n\n"
      : "";
  return existingContent + separator + MRP_META_PROMPT + "\n";
}

export interface MetaPromptResult {
  file: string;
  action: "injected" | "updated" | "created" | "skipped";
}

/**
 * Scan for known agent config files at projectRoot and inject/update the MRP meta-prompt.
 * - If file exists with markers: update the section
 * - If file exists without markers: inject (append) the section
 * - If file doesn't exist: create it with the MRP meta-prompt content
 */
export async function syncMetaPrompts(projectRoot: string): Promise<MetaPromptResult[]> {
  const results: MetaPromptResult[] = [];

  for (const fileName of AGENT_CONFIG_FILES) {
    const filePath = join(projectRoot, fileName);
    try {
      const content = await readFile(filePath, "utf-8");
      const hasMarkers = content.includes(START_MARKER);
      const updated = injectMetaPrompt(content);

      if (updated !== content) {
        await writeFile(filePath, updated, "utf-8");
        results.push({ file: fileName, action: hasMarkers ? "updated" : "injected" });
      } else {
        results.push({ file: fileName, action: "skipped" });
      }
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code === "ENOENT") {
        const fileContent = MRP_META_PROMPT + "\n";
        await writeFile(filePath, fileContent, "utf8");
        results.push({ file: fileName, action: "created" });
      } else {
        results.push({ file: fileName, action: "skipped" });
      }
    }
  }

  return results;
}
